# Allow importing this package
dashboard_import:
  package_import_url: 'github://noerrra/esphometemplates/shelly-plus-1/light-mode.yaml@main'
  import_full_config: false

light:
  - platform: binary
    name: "${device_name} Light"
    output: shelly_plus_1_relay
    id: lightid

binary_sensor:
  - platform: gpio
    name: "${device_name} Light"
    pin: GPIO4
    on_state:
      then:
        - light.toggle: lightid
    filters:
      - delayed_on_off: 50ms
    internal: true
